name: Compiler

on:
  push:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3

      - name: Build LaTeX
        run: |
          bash build.sh

      - name: Publish LaTeX
        run: |
          git config --global user.email "swemming.bot@pool.org"
          git config --global user.name "SwemmingBot"
          git add -f out
          git commit -m "SwemmingBot - Upload PDFs"
          git push
