name: Compiler

on:
  push:
    branches: [ main, dev, analisi_requisiti]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3

      - name: Latex-multicompiler
        uses: eliapasquali/Latex-multicompiler@vmaster
        with:
          path_to_list: .github/filesToCompile
          artifact: true

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Documenti compilati 
          path: Documents/*
