name: Compiler

on:
  push:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3

      - name: Latex-multicompiler
        uses: Jatus93/Latex-multicompiler@v1.0
        with:
          path_to_list: .github/filesToCompile
          artifact: true

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Documenti compilati 
          path: Documents/*
